name: py35
dependencies:
- openssl=1.0.2g=0
- pip=8.1.1=py35_0
- python=3.5.3
- readline=6.2=2
- sqlite
- tk
- wheel
- xz
- zlib
- pip:
  - sphinx_rtd_theme
    #  - sphinxjp.themes.basicstrap
  - sphinxcontrib-programoutput
  - vcf-annotation-tools
